"""
Zezelabs Holding OS — AppFactory Department Agent
Produces safe SaaS scaffolds inside workspace. No deploy, no git push, no external calls.

Pipeline:
  goal → PolicyEngine → WorkspaceGuard → ClawdeOperatorKernel.edit_file() → Telemetry → AgentResult
"""
from __future__ import annotations
import json
import os
import uuid
from datetime import datetime, timezone
from typing import Optional

from core.operator_runtime.contracts import (
    AgentResult, ToolRequest, RiskLevel, DepartmentName
)
from core.operator_runtime.policy_engine import PolicyEngine
from core.operator_runtime.clawde_kernel import ClawdeOperatorKernel
from core.operator_runtime.telemetry import get_telemetry

DEPARTMENT = "app_factory"


class AppFactoryAgent:
    """
    Autonomous SaaS scaffold producer.
    All file writes go through PolicyEngine + WorkspaceGuard.
    No external API calls, no git push, no deploy.
    """

    def __init__(
        self,
        workspace_root: str,
        policy_engine: Optional[PolicyEngine] = None,
        kernel: Optional[ClawdeOperatorKernel] = None,
    ):
        self.workspace_root = os.path.realpath(os.path.abspath(workspace_root))
        self.department = DepartmentName.APP_FACTORY
        self.policy = policy_engine or PolicyEngine(department=DEPARTMENT)
        self.kernel = kernel or ClawdeOperatorKernel(
            department=DEPARTMENT,
            workspace_root=self.workspace_root,
        )
        self.telemetry = get_telemetry()

    # ── Public API ─────────────────────────────────────────────────────────────
    def run_dry_task(self, goal: str, task_id: Optional[str] = None) -> AgentResult:
        """
        Run a safe scaffold dry-run for the given goal.
        Returns AgentResult with success status and file list.
        """
        task_id = task_id or str(uuid.uuid4())
        scaffold_dir = os.path.join(self.workspace_root, "app_factory", "todo_saas")
        created_files = []
        errors = []

        # ── Build scaffold manifest ────────────────────────────────────────────
        files_to_create = self._build_scaffold(goal, task_id, scaffold_dir)

        for rel_path, content in files_to_create.items():
            abs_path = os.path.join(scaffold_dir, rel_path)
            os.makedirs(os.path.dirname(abs_path), exist_ok=True)

            req = ToolRequest(
                tool_name="file_edit",
                action=f"create {rel_path}",
                task_id=task_id,
                department=DEPARTMENT,
                args={"path": abs_path, "content": content},
                risk_level=RiskLevel.LOW,
            )
            result = self.kernel.edit_file(req)

            if result.success:
                created_files.append(abs_path)
            else:
                errors.append(f"{rel_path}: {result.error}")

        success = len(errors) == 0
        output = (
            f"Scaffold created at {scaffold_dir}\nFiles: {len(created_files)}\n"
            + "\n".join(f"  ✅ {f}" for f in created_files)
        )
        if errors:
            output += "\nErrors:\n" + "\n".join(f"  ❌ {e}" for e in errors)

        self.telemetry.record_execution(
            task_id=task_id,
            department=DEPARTMENT,
            tool_name="app_factory_dry_run",
            action=goal[:80],
            status="success" if success else "partial_error",
            risk_level=RiskLevel.LOW.value,
            finished_at=datetime.now(timezone.utc),
        )

        return AgentResult(
            task_id=task_id,
            department=DEPARTMENT,
            success=success,
            output=output,
            tool_results=created_files,
            error="\n".join(errors) if errors else None,
        )

    # ── Scaffold Builder ───────────────────────────────────────────────────────
    def _build_scaffold(self, goal: str, task_id: str, scaffold_dir: str) -> dict:
        """Returns {relative_path: content} for all scaffold files."""
        return {
            "README.md": self._readme(goal, task_id),
            "manifest.json": self._manifest(goal, task_id),
            os.path.join("app", "main.py"): self._main_py(),
            os.path.join("tests", "test_smoke.py"): self._test_smoke(),
        }

    # ── Template Generators ────────────────────────────────────────────────────
    @staticmethod
    def _readme(goal: str, task_id: str) -> str:
        return f"""# Todo SaaS Scaffold
**Goal:** {goal}
**Task ID:** {task_id}
**Generated:** {datetime.now(timezone.utc).isoformat()}
**Department:** app_factory (Zezelabs Holding OS)

## Project Structure
```
app/
  main.py       # FastAPI application entrypoint
tests/
  test_smoke.py # Smoke tests
manifest.json   # Project manifest
README.md       # This file
```

## Getting Started
```bash
pip install fastapi uvicorn
uvicorn app.main:app --reload
```

> Generated by Zezelabs AppFactory. No deploy, no git push, no external calls.
"""

    @staticmethod
    def _manifest(goal: str, task_id: str) -> str:
        return json.dumps({
            "project": "todo_saas",
            "task_id": task_id,
            "goal": goal,
            "department": "app_factory",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "stack": ["python", "fastapi", "sqlite"],
            "status": "scaffold_dry_run",
            "deploy": False,
            "git_push": False,
            "live": False,
        }, indent=2)

    @staticmethod
    def _main_py() -> str:
        return '''"""
Todo SaaS — FastAPI Application (Scaffold)
Generated by Zezelabs AppFactory Dry-Run.
"""
from fastapi import FastAPI
from pydantic import BaseModel
from typing import List

app = FastAPI(title="Todo SaaS", version="0.1.0")

# In-memory store (replace with DB in production)
_todos: List[dict] = []


class TodoCreate(BaseModel):
    title: str
    done: bool = False


@app.get("/todos")
def list_todos():
    return _todos


@app.post("/todos")
def create_todo(todo: TodoCreate):
    item = {"id": len(_todos) + 1, **todo.dict()}
    _todos.append(item)
    return item


@app.put("/todos/{todo_id}")
def update_todo(todo_id: int, todo: TodoCreate):
    for t in _todos:
        if t["id"] == todo_id:
            t.update(todo.dict())
            return t
    return {"error": "not found"}


@app.delete("/todos/{todo_id}")
def delete_todo(todo_id: int):
    global _todos
    _todos = [t for t in _todos if t["id"] != todo_id]
    return {"deleted": todo_id}
'''

    @staticmethod
    def _test_smoke() -> str:
        return '''"""
Smoke tests for Todo SaaS scaffold.
Generated by Zezelabs AppFactory Dry-Run.
"""
from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)


def test_list_todos_empty():
    r = client.get("/todos")
    assert r.status_code == 200
    assert isinstance(r.json(), list)


def test_create_todo():
    r = client.post("/todos", json={"title": "Buy milk"})
    assert r.status_code == 200
    assert r.json()["title"] == "Buy milk"


def test_delete_todo():
    create = client.post("/todos", json={"title": "Temp"})
    todo_id = create.json()["id"]
    r = client.delete(f"/todos/{todo_id}")
    assert r.status_code == 200
    assert r.json()["deleted"] == todo_id
'''
